name: video_downloader_app
description: A video downloader frontend using Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  dio: ^5.3.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  gal: ^2.2.0
  # NEW PACKAGES:
  video_player: ^2.8.1
  chewie: ^1.7.1
  video_thumbnail: ^0.5.3
  flutter_local_notifications: ^18.0.1  # Upgraded to fix Android bigLargeIcon ambiguity
  intl: ^0.19.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: assets/icone.png
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: assets/icone.png
  windows:
    generate: true
    image_path: assets/icone.png
  macos:
    generate: true
    image_path: assets/icone.png
